# Generated by Django 5.0.6 on 2026-08-11 06:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EFECTUADO', 'Efectuado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='accounts.bankaccount')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='expenses.expense')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
