# Generated by Django 5.0.6 on 2026-08-11 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(help_text='Últimos 4 dígitos de la cuenta.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Deben ser 4 dígitos numéricos.')])),
                ('saldo_actual', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(choices=[('USD', 'Dólares'), ('MXN', 'Pesos Mexicanos'), ('EUR', 'Euros')], default='USD', max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
